development:
  adapter: postgresql
  database: nuller_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: nuller_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: nuller_production
  pool: 5
  timeout: 5000
